### ISSUE TITLE
Does not enforce the use of specific logic operators

### ISSUE THREAD

**Issue by jaegernh** [twodee/truxfalsy#1]
Cool game Chris!
When you request that a user us <=, for example y<=3, it allows y<4. 
Pretty easy to fix, just thought I'd recommend the change! Not sure if you care.

**Comment by twodee** [comment]
I do care. But I intentionally chose not to micromanage the user at this point in time. For one, I don't like games that do that to me. For two, players only hurt themselves by not exploring all the operators. For three, I want to embrace the idea that there are many ways to solve these puzzles. Sure, some answers are better than others, but that's not what I want to focus on.

Changing the language from "Use" to "Consider using" might mitigate the feelings of rebellion you get when you ignore the command.

Still, I do like the idea of a constrained "palette" and will keep it in mind for future generations. Thanks!
